### ISSUE TITLE
List error

### ISSUE THREAD

**Issue by leogaggl** [awong1900/wio-cli#11]
I have installed wio-cli as I can not set up via Nexus6P. I can login and state shows connected to main server (International).

When doing setup it connects to the main server and it detects a device connected via USB

wio setup
> Setup is easy! Let's get started...

! PROTIP: Hold the Configure button ~4s into Configure Mode!
! PROTIP: Please make sure you are connected to the main server

? Would you like continue? [Y/n]: y
-Getting message from main server...                                            \Getting message from main server...                                            |Getting message from main server...                                            /Getting message from main server...                                            -Getting message from main server...                                            \Getting message from main server...                                            |Getting message from main server...                                            /Getting message from main server...                                            -Getting message from main server...                                            \Getting message from main server...                                            |Getting message from main server...                                            /                                                                               > I have detected a Wiolink connected via USB.                                  
-Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |Getting device information...                                                  /Getting device information...                                                  -Getting device information...                                                  \Getting device information...                                                  |                                                                               /                                                                               > No nearby Wiolink detected.                                                   
? Would you like to wait and monitor for Wiolink entering configure mode [Y/n]:

When doing a "wio list" I get the following error:

wio list
-Retrieving devices...                                                          \Retrieving devices...                                                          |Retrieving devices...                                                          /Retrieving devices...                                                          -Retrieving devices...                                                          \Retrieving devices...                                                          |Retrieving devices...                                                          /Retrieving devices...                                                          -Retrieving devices...                                                          \Retrieving devices...                                                          |Retrieving devices...                                                          /Retrieving device APIs...                                                      -Retrieving device APIs...                                                      \Retrieving device APIs...                                                      |Retrieving device APIs...                                                      /Retrieving device APIs...                                                      -Retrieving device APIs...                                                      \Retrieving device APIs...                                                      |Retrieving device APIs...                                                      /Retrieving device APIs...                                                      -Retrieving device APIs...                                                      \Retrieving device APIs...                                                      |                                                                               /                                                                               Traceback (most recent call last):                                              
  File "/usr/local/bin/wio", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wio/wio.py", line 277, in list
    termui.tree(node_list)
  File "/usr/local/lib/python2.7/dist-packages/wio/termui.py", line 57, in tree
    l = list[-1]
IndexError: list index out of range
 

Let me know if I can assist with anything else. 

OS: Ubuntu 16.04

**Comment by leogaggl** [comment]
I worked out that when I chose "n" at this question: Would you like to wait and monitor for Wiolink entering configure mode [Y/n] you can then get chose to get into "Manual Setup" and once I did that I was able to set up.

As a suggestion could you:
1) create a "wio setup --manual" switch to go straight to manual setup via USB ?
2) detect no setup devices in the "wio list" instead of error above

Keep up the good work ! Thanks.

**Comment by awong1900** [comment]
Sorry to later reply.  Thanks for your advise.
